#!/bin/sh
/usr/lib64/subversion/contrib/hook-scripts/svnnotify --set-sender --repos-path "$1" --revision "$2" --to "docutils-checkins@lists.sourceforge.net" --subject-prefix "SF.net SVN: docutils:" --subject-cx --no-first-line --with-diff --viewcvs-url "http://sourceforge.net/p/docutils/code/%s" --user-domain "users.sourceforge.net" --footer "This was sent by the SourceForge.net collaborative development platform, the world's largest Open Source development site." -l /usr/bin/svnlook --max-diff-length 100000
exit 0
